-- Phase 5: paper validation cloud.
-- VMs send batched telemetry to api-ai; they never hold direct Postgres connections.

SET search_path = public;

CREATE TABLE IF NOT EXISTS validation_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  strategy_id uuid NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
  spec_hash text NOT NULL CHECK (spec_hash ~ '^[0-9a-f]{64}$'),
  mode text NOT NULL DEFAULT 'paper' CHECK (mode = 'paper'),
  exchange text NOT NULL CHECK (exchange IN ('binance','bybit')),
  status text NOT NULL DEFAULT 'provisioning'
    CHECK (status IN ('provisioning','running','passed','failed','cancelled','error')),
  idempotency_key text NOT NULL,
  fly_app_name text NOT NULL,
  fly_machine_id text,
  fly_region text NOT NULL,
  fly_fallback_regions text[] NOT NULL DEFAULT ARRAY[]::text[],
  lease_key text NOT NULL,
  ttl_expires_at timestamptz NOT NULL,
  estimated_cost_cents integer NOT NULL DEFAULT 0 CHECK (estimated_cost_cents >= 0),
  labels jsonb NOT NULL DEFAULT '{}'::jsonb,
  scorecard_thresholds jsonb NOT NULL DEFAULT '{}'::jsonb,
  scorecard_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  scorecard_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT validation_runs_idempotency_unique UNIQUE (user_id, idempotency_key),
  CONSTRAINT validation_runs_lease_unique UNIQUE (lease_key)
);

CREATE INDEX IF NOT EXISTS validation_runs_user_status_idx
  ON validation_runs (user_id, status);
CREATE INDEX IF NOT EXISTS validation_runs_ttl_idx
  ON validation_runs (ttl_expires_at);

CREATE TRIGGER validation_runs_set_updated_at
  BEFORE UPDATE ON validation_runs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE validation_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "validation_runs readable by owner"
  ON validation_runs FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY "validation_runs insertable by owner"
  ON validation_runs FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "validation_runs updatable by owner"
  ON validation_runs FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS validation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  validation_id uuid NOT NULL REFERENCES validation_runs(id) ON DELETE CASCADE,
  run_id text NOT NULL,
  seq bigint NOT NULL CHECK (seq >= 0),
  kind text NOT NULL CHECK (kind IN (
    'heartbeat','market_tick','order_intent','fill','risk_guard','exec_error',
    'rate_limit','clock_skew','scorecard'
  )),
  event_ts timestamptz NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  inserted_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT validation_events_seq_unique UNIQUE (validation_id, run_id, seq)
);

CREATE INDEX IF NOT EXISTS validation_events_validation_seq_idx
  ON validation_events (validation_id, seq);

ALTER TABLE validation_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "validation_events readable by validation owner"
  ON validation_events FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM validation_runs vr
      WHERE vr.id = validation_events.validation_id
      AND vr.user_id = auth.uid()
    )
  );

CREATE TABLE IF NOT EXISTS validation_heartbeats (
  validation_id uuid PRIMARY KEY REFERENCES validation_runs(id) ON DELETE CASCADE,
  run_id text NOT NULL,
  last_seq bigint NOT NULL DEFAULT 0,
  last_event_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE validation_heartbeats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "validation_heartbeats readable by validation owner"
  ON validation_heartbeats FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM validation_runs vr
      WHERE vr.id = validation_heartbeats.validation_id
      AND vr.user_id = auth.uid()
    )
  );

CREATE TABLE IF NOT EXISTS order_outbox (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  validation_id uuid REFERENCES validation_runs(id) ON DELETE CASCADE,
  strategy_id uuid NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
  client_order_id uuid NOT NULL,
  intent_id text NOT NULL,
  exchange text NOT NULL CHECK (exchange IN ('binance','bybit')),
  symbol text NOT NULL,
  side text NOT NULL CHECK (side IN ('buy','sell')),
  qty numeric NOT NULL CHECK (qty > 0),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending','acked','filled','rejected','cancelled')),
  last_reconciled_at timestamptz,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT order_outbox_client_order_unique UNIQUE (exchange, client_order_id)
);

CREATE INDEX IF NOT EXISTS order_outbox_reconcile_idx
  ON order_outbox (status, last_reconciled_at);

CREATE TRIGGER order_outbox_set_updated_at
  BEFORE UPDATE ON order_outbox
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE order_outbox ENABLE ROW LEVEL SECURITY;

CREATE POLICY "order_outbox readable by owner"
  ON order_outbox FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE TABLE IF NOT EXISTS paper_fills (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  validation_id uuid NOT NULL REFERENCES validation_runs(id) ON DELETE CASCADE,
  client_order_id uuid NOT NULL,
  exchange text NOT NULL CHECK (exchange IN ('binance','bybit')),
  symbol text NOT NULL,
  side text NOT NULL CHECK (side IN ('buy','sell')),
  qty numeric NOT NULL CHECK (qty > 0),
  price numeric NOT NULL CHECK (price > 0),
  filled_at timestamptz NOT NULL,
  slippage_bps numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS paper_fills_validation_idx
  ON paper_fills (validation_id, filled_at);

ALTER TABLE paper_fills ENABLE ROW LEVEL SECURITY;

CREATE POLICY "paper_fills readable by owner"
  ON paper_fills FOR SELECT TO authenticated
  USING (user_id = auth.uid());
